spring.application.name=qr-attendance-system

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.address=${SERVER_ADDRESS:0.0.0.0}
server.port=${SERVER_PORT:8085}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=never
server.error.include-binding-errors=never
